In [0]:
import numpy as np

In [0]:
#NumPy Arrays - One Dimensional

list = [1,2,'happy']
arr = np.array(list)

In [0]:
arr

array(['1', '2', 'happy'], dtype='<U11')

In [0]:
#NumPy Arrays - Multi Dimensional

list2 = [[1,2,'who'],[9,10,'pen'],[7,8,'late']]
arr2 = np.array(list2)
arr2

array([['1', '2', 'who'],
       ['9', '10', 'pen'],
       ['7', '8', 'late']], dtype='<U11')

In [0]:
np.arange(0,10) #Array using Built-in functions

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [0]:
np.zeros(3)   # For generating 1s, we also have np.ones() method.

array([0., 0., 0.])

In [0]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [0]:
np.linspace(1,3,12) #prints 12 equidistant position between 1 and 3

array([1.        , 1.18181818, 1.36363636, 1.54545455, 1.72727273,
       1.90909091, 2.09090909, 2.27272727, 2.45454545, 2.63636364,
       2.81818182, 3.        ])

In [0]:
np.eye(5) #identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
#Generating Random Numbers from a uniform distribution of numbers (0-1) using NumPy

np.random.rand(5)

array([0.35340864, 0.01665034, 0.71449472, 0.39479299, 0.32321078])

In [0]:
np.random.rand(2,2)

array([[0.87936607, 0.26182144],
       [0.75163589, 0.0317199 ]])

In [0]:
#Generating Random Numbers from a non-uniform distribution of numbers (0-1) using NumPy

np.random.randn(5)

array([-0.41206956,  1.01684674, -1.17913831,  0.11929753,  0.21729317])

In [0]:
np.random.randn(3,2)

array([[ 0.23736043,  0.67670082],
       [-0.42908785,  1.00255912],
       [ 0.54113683, -0.00341979]])

In [0]:
np.random.randint(1,100,15) #random integers within a given limit (inclusive on low-end, exclusive on high-end)

array([17, 61, 83, 75, 39, 18, 76,  8, 54, 83, 84, 13, 92, 78, 72])

In [0]:
# Array Operations

arr = np.arange(16)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [0]:
randarr = np.random.randint(0,50,25)

In [0]:
randarr

array([32, 46, 45,  8,  2, 30, 11, 17, 30,  5,  9, 35, 21, 43, 26, 18,  4,
       43, 49,  1, 47, 38, 25, 25, 28])

In [0]:
arr.reshape(4,4)  # reshaping an array into different dimensions

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
randarr.reshape(5,5)

array([[32, 46, 45,  8,  2],
       [30, 11, 17, 30,  5],
       [ 9, 35, 21, 43, 26],
       [18,  4, 43, 49,  1],
       [47, 38, 25, 25, 28]])

In [0]:
randarr.max()

49

In [0]:
randarr.min()

1

In [0]:
randarr.argmax() # Finds the position of the maximum element

18

In [0]:
arr.shape # Returns the shape of the array

(16,)

In [0]:
randarr.dtype

dtype('int32')

                                                Indexing and Selection In NumPy

In [0]:
arr = np.arange(0,15)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
arr[7:]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

  The only difference between a NumPy array and a List is that NumPy arrays can broadcast a particular value to selected positions within the array. i.e.,
  
  

In [0]:
arr[2:8] = 23

In [0]:
arr

array([ 0,  1, 23, 23, 23, 23, 23, 23,  8,  9, 10, 11, 12, 13, 14])

In [0]:
arr = np.arange(0,15)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
sliceofarr = arr[0:12]

In [0]:
sliceofarr[2:10] = 69

In [0]:
sliceofarr

array([ 0,  1, 69, 69, 69, 69, 69, 69, 69, 69, 10, 11])

In [0]:
arr

array([ 0,  1, 69, 69, 69, 69, 69, 69, 69, 69, 10, 11, 12, 13, 14])

In [0]:
arr_copy = arr.copy()

In [0]:
arr_copy


array([ 0,  1, 69, 69, 69, 69, 69, 69, 69, 69, 10, 11, 12, 13, 14])

In [0]:
arr_2d = np.array([[2,3,4],[8,6,7],[6,3,1]])

In [0]:
arr_2d

array([[2, 3, 4],
       [8, 6, 7],
       [6, 3, 1]])

In [0]:
arr_2d[1] [0]

8

In [0]:
arr_2d[:2,3:]

array([], shape=(2, 0), dtype=int32)

In [0]:
arr_2d > 5

array([[False, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [0]:
arr_2d[1:5,3:10]

array([], shape=(2, 0), dtype=int32)